# Generated by Django 2.2 on 2022-06-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detected',
            name='photo',
            field=models.ImageField(default='app/static/img/nobody.jpg', upload_to='detected/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(default='static/img/nobody.jpg', upload_to='images'),
        ),
    ]
